python main.py --base textual_inversion-main/configs/stable-diffusion/add_mask_180flip_128linear_lifang.yaml -t --actual_resume textual_inversion-main/models/v1-5-pruned.ckpt -n SD_visa_addmask --gpus 0,1 --data_root data/visa_generate/pcb1 --init_word Process Control Block
python main.py --base textual_inversion-main/configs/stable-diffusion/add_mask_180flip_128linear_lifang.yaml -t --actual_resume textual_inversion-main/models/v1-5-pruned.ckpt -n SD_visa_addmask --gpus 0,1 --data_root data/visa_generate/pcb2 --init_word Process Control Block
python main.py --base textual_inversion-main/configs/stable-diffusion/add_mask_180flip_128linear_lifang.yaml -t --actual_resume textual_inversion-main/models/v1-5-pruned.ckpt -n SD_visa_addmask --gpus 0,1 --data_root data/visa_generate/pcb3 --init_word Process Control Block
python main.py --base textual_inversion-main/configs/stable-diffusion/add_mask_no_flip_512linear_lifang.yaml -t --actual_resume textual_inversion-main/models/v1-5-pruned.ckpt -n SD_visa_addmask --gpus 0,1 --data_root data/visa_generate/pcb4 --init_word Process Control Block
python main.py --base textual_inversion-main/configs/latent-diffusion/add_mask_no_flip.yaml -t --actual_resume textual_inversion-main/models/model.ckpt -n LD_visa_addmask --gpus 0,1 --data_root data/visa_generate/macaroni1 --init_word screw
python main.py --base textual_inversion-main/configs/latent-diffusion/txt2img-1p4B-finetune.yaml -t --actual_resume textual_inversion-main/models/model.ckpt -n LD_visa --gpus 0,1 --data_root data/visa_generate/macaroni2 --init_word candle
python main.py --base textual_inversion-main/configs/stable-diffusion/v1-finetune.yaml -t --actual_resume textual_inversion-main/models/v1-5-pruned.ckpt -n SD_visa --gpus 0,1 --data_root data/visa_generate/capsules --init_word Process Control Block
python main.py --base textual_inversion-main/configs/latent-diffusion/add_mask_no_flip.yaml -t --actual_resume textual_inversion-main/models/model.ckpt -n LD_visa_addmask --gpus 0,1 --data_root data/visa_generate/candle --init_word screw
python main.py --base textual_inversion-main/configs/stable-diffusion/add_mask_no_flip_128linear_average.yaml -t --actual_resume textual_inversion-main/models/v1-5-pruned.ckpt -n SD_visa_addmask --gpus 0,1 --data_root data/visa_generate/cashew --init_word Process Control Block
python main.py --base textual_inversion-main/configs/stable-diffusion/add_mask_180flip.yaml -t --actual_resume textual_inversion-main/models/v1-5-pruned.ckpt -n SD_visa_addmask --gpus 0,1 --data_root data/visa_generate/chewinggum --init_word Process Control Block
python main.py --base textual_inversion-main/configs/stable-diffusion/add_mask_180flip_512linear_lifang.yaml -t --actual_resume textual_inversion-main/models/v1-5-pruned.ckpt -n SD_visa_addmask --gpus 0,1 --data_root data/visa_generate/fryum --init_word Process Control Block